// This file is auto-generated by Supabase CLI.
// Run: npm run db:generate-types
// Manual types below are placeholders until you run the generator.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type MilitaryBranch =
  | 'army' | 'navy' | 'marine_corps' | 'air_force'
  | 'space_force' | 'coast_guard' | 'national_guard' | 'reserves'

export type SubscriptionTier = 'free' | 'pro' | 'elite'

export type OrgType = 'vso' | 'legal' | 'tap_program' | 'employer' | 'nonprofit' | 'government'

export type OrgMemberRole = 'member' | 'case_manager' | 'admin' | 'owner'

export type ClaimStatus =
  | 'not_started' | 'gathering_evidence' | 'submitted'
  | 'in_review' | 'decision_received' | 'appealing' | 'closed'

export type MilestoneStatus = 'pending' | 'in_progress' | 'complete' | 'skipped'

export type DocumentType = 'dd214' | 'medical_record' | 'service_record' | 'va_letter' | 'noa' | 'other'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          full_name: string | null
          email: string | null
          avatar_url: string | null
          phone: string | null
          branch: MilitaryBranch | null
          mos_code: string | null
          mos_title: string | null
          rank: string | null
          years_of_service: number | null
          separation_date: string | null
          ets_date: string | null
          deployment_count: number
          combat_vet: boolean
          security_clearance: string | null
          transition_started_at: string | null
          is_transitioning: boolean
          tier: SubscriptionTier
          stripe_customer_id: string | null
          subscription_id: string | null
          location_city: string | null
          location_state: string | null
          target_industry: string[] | null
          target_roles: string[] | null
          onboarding_complete: boolean
          terms_accepted_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      organizations: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          name: string
          slug: string
          org_type: OrgType
          website: string | null
          description: string | null
          logo_url: string | null
          primary_color: string
          custom_domain: string | null
          stripe_customer_id: string | null
          subscription_id: string | null
          plan: string
          seat_count: number
          max_seats: number
          contact_name: string | null
          contact_email: string | null
          is_active: boolean
          verified_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>
      }
      org_members: {
        Row: {
          id: string
          created_at: string
          org_id: string
          user_id: string
          role: OrgMemberRole
          invited_by: string | null
          joined_at: string
          notes: string | null
        }
        Insert: Omit<Database['public']['Tables']['org_members']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['org_members']['Insert']>
      }
      va_claims: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          condition_name: string
          status: ClaimStatus
          claim_number: string | null
          filed_date: string | null
          decision_date: string | null
          rating_percent: number | null
          notes: string | null
          ai_guidance: Json | null
          evidence_list: string[] | null
        }
        Insert: Omit<Database['public']['Tables']['va_claims']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['va_claims']['Insert']>
      }
      transition_plans: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          ets_date: string | null
          started_at: string
          completed_at: string | null
          progress_pct: number
        }
        Insert: Omit<Database['public']['Tables']['transition_plans']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['transition_plans']['Insert']>
      }
      resumes: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          user_id: string
          title: string
          target_role: string | null
          target_company: string | null
          content: string
          ai_version: boolean
          ats_score: number | null
          is_primary: boolean
          storage_path: string | null
        }
        Insert: Omit<Database['public']['Tables']['resumes']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['resumes']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      is_org_admin: { Args: { p_org_id: string }; Returns: boolean }
      is_org_member: { Args: { p_org_id: string }; Returns: boolean }
      my_admin_org_ids: { Args: Record<string, never>; Returns: string[] }
      my_org_member_ids: { Args: Record<string, never>; Returns: string[] }
    }
    Enums: {
      military_branch: MilitaryBranch
      subscription_tier: SubscriptionTier
      org_type: OrgType
      org_member_role: OrgMemberRole
      claim_status: ClaimStatus
      milestone_status: MilestoneStatus
      document_type: DocumentType
    }
  }
}
